### ISSUE TITLE
Display summary statistics

### ISSUE THREAD

**Issue by penguinyaro** [HACC2022/SquidBrainsAreShapedLikeDonuts#10]
After pulling data summarize data
- Features
- Feature types
- Number of unique values
- Unique values (up to a small amount)
- Types of displays possible (e.g. count)

**Comment by penguinyaro** [comment]
Strings
- Count

Numbers
- Count
- Sum
- Average

**Comment by penguinyaro** [comment]
Reference: https://pandas.pydata.org/

**Comment by hmurai8** [comment]
- Display summary of data
- Also guide for user as he goes along (suggesting what values to choose in pivot table based off of what is given in data summary) e.g. suggesting to use values that aren't unique, columns will be ideally 10 or less fields

**Comment by hmurai8** [comment]
- info() and describe() make user aware of basic dataset features
- dtypes() to show user current columns + data types
- nunique() to show number of unique values for each column revealing which columns have most and least unique values. This tells user to pick column with least unique values when customizing
- Types of displays possible (bar, histogram, and pie chart?)

**Comment by hmurai8** [comment]
- User guide to help user customize most helpful data visualizations after seeing data summary (what you should be looking for in certain fields and what type of chart fits best for certain types of data)

**Comment by penguinyaro** [comment]
> * User guide to help user customize most helpful data visualizations after seeing data summary (what you should be looking for in certain fields and what type of chart fits best for certain types of data)

@Eric this is the one we need your help with. Maybe you and @hmurai8 have discussed this on your google doc?

**Comment by hmurai8** [comment]
Numeric data features: (instead of describe)
df.agg(['count', 'min', 'max', 'mean', 'sum'])
Not sure how to make numeric_only = True, so that objects don't do this

**Comment by hmurai8** [comment]
pd.set_option('display.float_format', lambda x: '%.0f' % x)
    current_columns = df.columns #list
    types = df.dtypes
    unique = df.nunique()
    total = df.sum(numeric_only=True)
    agg = df.describe().loc[['count','max', 'min', 'mean']]

Used these so far
