### ISSUE TITLE
Come up with a name for the final product

### ISSUE THREAD

**Issue by penguinyaro** [HACC2022/SquidBrainsAreShapedLikeDonuts#7]
What should we name this thing?

Something meaningful? Something funny?

**Comment by hmurai8** [comment]
Something simple? Data vision; SimplyData; DataSmart; DataLens?
Something more creative? Dynamite Data; Visual Sesame; Data Sesame; Data,Set,Go?

**Comment by penguinyaro** [comment]
![DALL·E 2022-10-30 21 22 02 - a nerdy squid creating charts](https://user-images.githubusercontent.com/15057517/199381293-acddd511-bcb7-4e9c-a2c0-23dc50eabb49.png)
Squid Brain Charts was decided upon.
